name: Production Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: [self-hosted, staging]
    steps:
      - name: Deploy Web Application on Prod VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_VM_SSH_KEY }}
          VM_USERNAME: ${{ secrets.PROD_VM_USERNAME }}
          VM_IP: ${{ secrets.PROD_VM_IP }}
        run: |
      
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts
          
          ssh -i ~/.ssh/id_rsa $VM_USERNAME@$VM_IP << 'EOF'
            set -e
            
            TARGET_DIR="$HOME/web-app-deployment"
            
            if [ ! -d "$TARGET_DIR" ]; then
              echo "Cloning repository for the first time..."
              git clone https://github.com/ankitroutnetsmartz-ctrl/CI-CD-Pipeline.git "$TARGET_DIR"
              cd "$TARGET_DIR"
            else
              echo "Updating existing deployment files..."
              cd "$TARGET_DIR"
              git fetch origin
              git reset --hard origin/main
            fi

            docker compose up -d --build

            docker image prune -f
          EOF
